-- ============================================================
-- ATARA — Sistema Web de Alertas Tempranas y Análisis del
--         Rendimiento Académico
--
-- Base de datos : PostgreSQL 15+
-- Esquema       : public
-- Versión       : V1 (Flyway)
-- Codificación  : UTF-8
--
-- ORDEN DE TABLAS (respeta dependencias FK):
--   1.  roles
--   2.  anios_lectivos         (+ updated_at, UNIQUE parcial activo)
--   3.  niveles
--   4.  escalas_valoracion
--   5.  dimensiones_evaluacion (+ updated_at) — antes que criterios_indicadores
--   6.  centros_educativos     (+ updated_at)
--   7.  materias               (+ updated_at)
--   8.  periodos               (+ updated_at, UNIQUE parcial activo por anio)
--   9.  usuarios               (+ apellidos, estado, ultimo_acceso, updated_at)
--  10.  secciones              (nivel_id FK en lugar de nivel VARCHAR, updated_at)
--  11.  usuarios_secciones     (M:N docente-seccion)
--  12.  estudiantes            (datos personales estables; sin seccion_id)
--  13.  matriculas             (asignación histórica estudiante↔sección por año lectivo)
--  14.  contenidos             (+ updated_at, UNIQUE por materia)
--  15.  criterios_indicadores  (+ peso, updated_at, dimension_id NOT NULL)
--  16.  configuracion_alertas  (+ dimension_id FK nullable, updated_at)
--  17.  evaluaciones           (+ seccion_id denormalizado, UNIQUE, updated_at)
--  18.  detalle_evaluacion     (solo criterio_id + escala_id — 3NF)
--  19.  alertas                (+ evaluacion_id FK nullable, generada_por, updated_at)
--  20.  tokens_refresh         (gestión JWT — almacena hash SHA-256)
--  21.  registro_auditoria     (registro_id BIGINT, JSONB antes/después)
--

-- ============================================================


-- ============================================================
-- 1. ROLES -- DATOS FIJOS
-- ============================================================
-- Tabla que almacena los roles del sistema: ADMIN, DOCENTE y COORDINADOR.
CREATE TABLE roles (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50)  NOT NULL
                    CONSTRAINT uq_rol_nombre UNIQUE,
    descripcion TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE roles IS 'Catálogo de roles del sistema: ADMIN, DOCENTE, COORDINADOR.';


-- ============================================================
-- 2. AÑOS LECTIVOS -- DATOS FLEXIBLES
-- ============================================================
-- Tabla que registra los años lectivos con sus fechas de inicio y fin.
CREATE TABLE anios_lectivos (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio        SMALLINT    NOT NULL
                    CONSTRAINT uq_anio_lectivo UNIQUE,
    fecha_inicio DATE        NOT NULL,
    fecha_fin    DATE        NOT NULL,
    activo       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_anio_rango   CHECK (anio BETWEEN 2000 AND 2200),
    CONSTRAINT chk_anio_fechas  CHECK (fecha_fin > fecha_inicio)
);

-- Índice único parcial para garantizar que solo exista un año lectivo activo a la vez.
CREATE UNIQUE INDEX uq_un_anio_activo
    ON anios_lectivos (activo)
    WHERE activo = TRUE;

-- Índice para acelerar consultas que filtran por el estado activo del año lectivo.
CREATE INDEX idx_anios_activo ON anios_lectivos (activo);

COMMENT ON TABLE  anios_lectivos        IS 'Año escolar (ej. 2025). Solo uno puede estar activo.';
COMMENT ON COLUMN anios_lectivos.activo IS 'TRUE = año en curso. Índice parcial garantiza unicidad.';


-- ============================================================
-- 3. NIVELES ACADÉMICOS  (1° – 6° primaria) -- DATOS FIJOS
-- ============================================================
-- Tabla de los grados académicos de primaria, del 1° al 6°.
CREATE TABLE niveles (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_grado   SMALLINT    NOT NULL
                       CONSTRAINT uq_nivel_grado UNIQUE,
    nombre         VARCHAR(100) NOT NULL
                       CONSTRAINT uq_nivel_nombre UNIQUE,
    descripcion    TEXT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_grado_rango CHECK (numero_grado BETWEEN 1 AND 6)
);

COMMENT ON TABLE  niveles              IS 'Catálogo fijo: grados 1° a 6° de educación primaria.';
COMMENT ON COLUMN niveles.numero_grado IS '1 = Primer Grado … 6 = Sexto Grado.';


-- ============================================================
-- 4. ESCALAS DE VALORACIÓN  (Likert 1-4) -- DATOS FIJOS
-- ============================================================
-- Tabla con los niveles de valoración del desempeño, de Insuficiente a Destacado.
CREATE TABLE escalas_valoracion (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(50)  NOT NULL
                        CONSTRAINT uq_escala_nombre UNIQUE,
    etiqueta        CHAR(1)      NOT NULL
                        CONSTRAINT uq_escala_etiqueta UNIQUE,
    valor_numerico  SMALLINT     NOT NULL
                        CONSTRAINT uq_escala_valor UNIQUE,
    descripcion     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_escala_valor CHECK (valor_numerico BETWEEN 1 AND 4)
);

COMMENT ON TABLE  escalas_valoracion                IS 'Escala Likert 1-4: I, B, S, D.';
COMMENT ON COLUMN escalas_valoracion.valor_numerico IS '1=Insuficiente 2=Básico 3=Satisfactorio 4=Destacado';


-- ============================================================
-- 5. DIMENSIONES DE EVALUACIÓN -- DATOS FIJOS
--    Se crea ANTES que criterios_indicadores y configuracion_alertas
--    porque ambas tablas referencian dimension_id.
-- ============================================================
-- Tabla de los ejes o categorías usados para evaluar el desempeño de los estudiantes.
CREATE TABLE dimensiones_evaluacion (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(150) NOT NULL
                    CONSTRAINT uq_dimension_nombre UNIQUE,
    descripcion TEXT,
    peso        NUMERIC(5,2) NOT NULL DEFAULT 1.0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_dimension_peso CHECK (peso > 0)
);

COMMENT ON TABLE  dimensiones_evaluacion      IS 'Ejes de evaluación: Rendimiento Académico, Participación, Hábitos, Socioemocional, Asistencia.';
COMMENT ON COLUMN dimensiones_evaluacion.peso IS 'Peso relativo al calcular promedios ponderados.';


-- ============================================================
-- 6. CENTROS EDUCATIVOS -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de las escuelas primarias registradas en el sistema.
CREATE TABLE centros_educativos (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(200) NOT NULL
                            CONSTRAINT uq_centro_nombre UNIQUE,
    circuito            VARCHAR(10),
    direccion_regional  VARCHAR(100),
    telefono            VARCHAR(20),
    correo              VARCHAR(150),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE centros_educativos IS 'Escuelas primarias registradas en el sistema. Quedaria abierto para que agreguen las necesarias';


-- ============================================================
-- 7. MATERIAS -- DATOS FIJOS
-- ============================================================
-- Tabla de las áreas curriculares que se imparten (Matemáticas, Español, Ciencias, etc.).
CREATE TABLE materias (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL
                    CONSTRAINT uq_materia_nombre UNIQUE,
    descripcion TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE materias IS 'Áreas curriculares: Matemáticas, Español, Ciencias, Estudios Sociales.';


-- ============================================================
-- 8. PERÍODOS  (ventanas de evaluación) -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de los períodos de evaluación dentro de cada año lectivo.
CREATE TABLE periodos (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio_lectivo_id INT         NOT NULL
                        REFERENCES anios_lectivos(id) ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    nombre          VARCHAR(100) NOT NULL,
    numero_periodo  SMALLINT    NOT NULL,
    fecha_inicio    DATE        NOT NULL,
    fecha_fin       DATE        NOT NULL,
    activo          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_periodo_por_anio   UNIQUE (anio_lectivo_id, numero_periodo),
    CONSTRAINT chk_periodo_numero    CHECK  (numero_periodo BETWEEN 1 AND 6),
    CONSTRAINT chk_periodo_fechas    CHECK  (fecha_fin > fecha_inicio)
);

-- Índice único parcial para garantizar que solo haya un período activo por año lectivo.
CREATE UNIQUE INDEX uq_periodo_activo_por_anio
    ON periodos (anio_lectivo_id)
    WHERE activo = TRUE;

-- Índice para acelerar búsquedas de períodos por año lectivo.
CREATE INDEX idx_periodos_anio   ON periodos (anio_lectivo_id);
-- Índice para acelerar consultas que filtran por el estado activo del período.
CREATE INDEX idx_periodos_activo ON periodos (activo);

COMMENT ON TABLE  periodos        IS 'Períodos trimestral o cuatrimestre de evaluación dentro de un año lectivo.';
COMMENT ON COLUMN periodos.activo IS 'TRUE = período de evaluación en curso. Índice parcial garantiza unicidad por año.';


-- ============================================================
-- 9. USUARIOS -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de los usuarios del sistema: administradores, docentes y coordinadores.
CREATE TABLE usuarios (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    apellidos     VARCHAR(150) NOT NULL,
    correo        VARCHAR(150) NOT NULL
                      CONSTRAINT uq_usuario_correo UNIQUE,
    password      VARCHAR(255) NOT NULL,   -- BCrypt 60 chars — nunca texto plano
    rol_id        INT         NOT NULL
                      REFERENCES roles(id) ON DELETE RESTRICT
                      DEFERRABLE INITIALLY IMMEDIATE,
    estado        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    ultimo_acceso TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_usuario_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- Índice para acelerar búsquedas de usuarios por rol.
CREATE INDEX idx_usuarios_rol    ON usuarios (rol_id);
-- Índice para acelerar consultas que filtran por el estado del usuario.
CREATE INDEX idx_usuarios_estado ON usuarios (estado);

COMMENT ON TABLE  usuarios          IS 'Usuarios del sistema: ADMIN, DOCENTE y COORDINADOR.';
COMMENT ON COLUMN usuarios.password IS 'Hash BCrypt (exactamente 60 caracteres). Ver ACCIÓN REQUERIDA en README.';


-- ============================================================
-- 10. SECCIONES -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de los grupos de clase formados por grado, centro y año lectivo.
CREATE TABLE secciones (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(10)  NOT NULL,   -- 'A', 'B', 'C', …
    nivel_id        INT          NOT NULL
                        REFERENCES niveles(id)            ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    centro_id       INT          NOT NULL
                        REFERENCES centros_educativos(id) ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    anio_lectivo_id INT          NOT NULL
                        REFERENCES anios_lectivos(id)     ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    docente_id      INT
                        REFERENCES usuarios(id)           ON DELETE SET NULL
                        DEFERRABLE INITIALLY IMMEDIATE,
    capacidad       SMALLINT     CHECK (capacidad > 0),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_seccion UNIQUE (nivel_id, centro_id, anio_lectivo_id, nombre)
);

-- Índice para acelerar búsquedas de secciones por nivel académico.
CREATE INDEX idx_secciones_nivel   ON secciones (nivel_id);
-- Índice para acelerar búsquedas de secciones por centro educativo.
CREATE INDEX idx_secciones_centro  ON secciones (centro_id);
-- Índice para acelerar búsquedas de secciones por año lectivo.
CREATE INDEX idx_secciones_anio    ON secciones (anio_lectivo_id);
-- Índice para acelerar consultas de secciones asignadas a un docente.
CREATE INDEX idx_secciones_docente ON secciones (docente_id);

COMMENT ON TABLE  secciones            IS 'Grupo-aula: combinación única de nivel, centro, año lectivo y letra.';
COMMENT ON COLUMN secciones.docente_id IS 'Docente titular. Otros docentes asignados via usuarios_secciones esta opcion es opcional .';


-- ============================================================
-- 11. USUARIOS ↔ SECCIONES  (M:N) -- DATOS FLEXIBLES
-- ============================================================
-- Tabla intermedia que asigna docentes o coordinadores a una o más secciones.
CREATE TABLE usuarios_secciones (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INT NOT NULL
                    REFERENCES usuarios(id)  ON DELETE CASCADE
                    DEFERRABLE INITIALLY IMMEDIATE,
    seccion_id  INT NOT NULL
                    REFERENCES secciones(id) ON DELETE CASCADE
                    DEFERRABLE INITIALLY IMMEDIATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_usuario_seccion UNIQUE (usuario_id, seccion_id)
);

-- Índice para acelerar búsquedas de asignaciones por usuario.
CREATE INDEX idx_us_usuario ON usuarios_secciones (usuario_id);
-- Índice para acelerar búsquedas de asignaciones por sección.
CREATE INDEX idx_us_seccion ON usuarios_secciones (seccion_id);

COMMENT ON TABLE usuarios_secciones IS 'Docentes (o coordinadores) asignados a una o más secciones. Es diferente a la tabla secciones ya que es mas como para agregar a mas profesores relacionadas a la seccion .';


-- ============================================================
-- 12. ESTUDIANTES -- DATOS FLEXIBLES
--
--  Almacena únicamente los datos personales estables del estudiante.
--  La asignación a secciones a lo largo de los años lectivos se
--  gestiona en la tabla matriculas (tabla 13).
-- ============================================================
-- Tabla con los datos personales estables de cada estudiante.
CREATE TABLE estudiantes (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion      VARCHAR(25)  NOT NULL UNIQUE,  -- código institucional o cédula de identidad
    nombre              VARCHAR(100) NOT NULL,
    apellido1           VARCHAR(100) NOT NULL,
    apellido2           VARCHAR(100),
    fecha_nacimiento    DATE,
    genero              CHAR(1)      CHECK (genero IN ('M', 'F', 'O')),
    nombre_acudiente    VARCHAR(200),
    telefono_acudiente  VARCHAR(20),
    correo_acudiente    VARCHAR(150),
    estado              VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_estudiante_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'TRASLADADO'))
);

-- Índice para acelerar consultas que filtran estudiantes por estado.
CREATE INDEX idx_estudiantes_estado    ON estudiantes (estado);
-- Índice para acelerar búsquedas de estudiantes por apellido y nombre.
CREATE INDEX idx_estudiantes_apellido1 ON estudiantes (apellido1, nombre);

COMMENT ON TABLE  estudiantes IS
    'Datos personales estables del estudiante (nombre, identificacion, acudiente, etc.). '
    'La asignación a secciones por año lectivo se registra en la tabla matriculas.';
COMMENT ON COLUMN estudiantes.identificacion IS 'Obligatorio y único; código institucional o cédula de identidad del estudiante.';
COMMENT ON COLUMN estudiantes.estado         IS 'Estado global del estudiante. TRASLADADO = salió de la institución. Detalle de cada año lectivo en matriculas.';


-- ============================================================
-- 13. MATRÍCULAS  (asignación histórica estudiante ↔ sección)
--
--  Relaciona cada estudiante con la sección que le corresponde
--  en un año lectivo específico.
--
--  Regla de negocio principal:
--    UNIQUE (estudiante_id, anio_lectivo_id) garantiza que un
--    estudiante no puede estar en dos secciones distintas
--    dentro del mismo año lectivo.
--
--  anio_lectivo_id es redundante con secciones.anio_lectivo_id
--  pero se incluye aquí de forma deliberada para poder aplicar
--  la restricción de unicidad directamente en esta tabla,
--  siguiendo el mismo patrón que evaluaciones.seccion_id.
-- ============================================================
-- Tabla que registra en qué sección estuvo matriculado un estudiante en cada año lectivo.
CREATE TABLE matriculas (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id   INT          NOT NULL
                        REFERENCES estudiantes(id)    ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    seccion_id      INT          NOT NULL
                        REFERENCES secciones(id)      ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    anio_lectivo_id INT          NOT NULL              -- denormalizado para poder aplicar UNIQUE por año
                        REFERENCES anios_lectivos(id) ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    estado          VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    fecha_matricula DATE         NOT NULL DEFAULT CURRENT_DATE,
    observaciones   TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_estudiante_por_anio UNIQUE (estudiante_id, anio_lectivo_id),
    CONSTRAINT chk_matricula_estado   CHECK  (estado IN ('ACTIVO', 'RETIRADO'))
);

-- Índice para consultar todas las matrículas de un estudiante a lo largo de los años.
CREATE INDEX idx_matriculas_estudiante ON matriculas (estudiante_id);
-- Índice para listar todos los estudiantes matriculados en una sección.
CREATE INDEX idx_matriculas_seccion    ON matriculas (seccion_id);
-- Índice para filtrar matrículas por año lectivo.
CREATE INDEX idx_matriculas_anio       ON matriculas (anio_lectivo_id);
-- Índice para filtrar matrículas por estado de la inscripción.
CREATE INDEX idx_matriculas_estado     ON matriculas (estado);

COMMENT ON TABLE  matriculas                 IS 'Historial de asignación estudiante↔sección por año lectivo. UNIQUE (estudiante_id, anio_lectivo_id) garantiza una sola sección por año.';
COMMENT ON COLUMN matriculas.anio_lectivo_id IS 'Denormalizado desde secciones.anio_lectivo_id para poder aplicar UNIQUE (estudiante_id, anio_lectivo_id) en esta tabla.';
COMMENT ON COLUMN matriculas.estado          IS 'ACTIVO = cursando normalmente. RETIRADO = abandonó la institución durante el año lectivo.';


-- ============================================================
-- 14. CONTENIDOS -- DATOS FIJOS
-- ============================================================
-- Tabla de las unidades temáticas que pertenecen a cada materia.
CREATE TABLE contenidos (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(200) NOT NULL,
    descripcion TEXT,
    materia_id  INT          NOT NULL
                    REFERENCES materias(id) ON DELETE RESTRICT
                    DEFERRABLE INITIALLY IMMEDIATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_contenido_por_materia UNIQUE (materia_id, nombre)
);

-- Índice para acelerar búsquedas de contenidos por materia.
CREATE INDEX idx_contenidos_materia ON contenidos (materia_id);

COMMENT ON TABLE contenidos IS 'Unidades temáticas dentro de cada materia.';


-- ============================================================
-- 15. CRITERIOS / INDICADORES -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de las "preguntas" o ítems de las evaluaciónes vinculadas a contenidos y dimensiones.
CREATE TABLE criterios_indicadores (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(200) NOT NULL,
    descripcion  TEXT,
    contenido_id INT          NOT NULL
                     REFERENCES contenidos(id)             ON DELETE RESTRICT
                     DEFERRABLE INITIALLY IMMEDIATE,
    dimension_id INT          NOT NULL
                     REFERENCES dimensiones_evaluacion(id) ON DELETE RESTRICT
                     DEFERRABLE INITIALLY IMMEDIATE,
    peso         NUMERIC(5,2) NOT NULL DEFAULT 1.0,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_criterio_por_contenido UNIQUE (contenido_id, nombre),
    CONSTRAINT chk_criterio_peso         CHECK  (peso > 0)
);

-- Índice para acelerar búsquedas de criterios por contenido.
CREATE INDEX idx_criterios_contenido ON criterios_indicadores (contenido_id);
-- Índice para acelerar búsquedas de criterios por dimensión de evaluación.
CREATE INDEX idx_criterios_dimension ON criterios_indicadores (dimension_id);

COMMENT ON TABLE  criterios_indicadores              IS 'Ítems observables evaluados con escala Likert 1-4.';
COMMENT ON COLUMN criterios_indicadores.dimension_id IS 'Obligatorio. Dimensión de evaluación a la que pertenece el criterio.';


-- ============================================================
-- 16. CONFIGURACIÓN DE ALERTAS  (motor de reglas) -- DATOS FLEXIBLES
-- ============================================================
-- Tabla con las reglas del sistema de alertas tempranas y sus umbrales de activación.
CREATE TABLE configuracion_alertas (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(200) NOT NULL,
    descripcion      TEXT,
    umbral_minimo    NUMERIC(5,2),
    umbral_maximo    NUMERIC(5,2),
    tipo_alerta      VARCHAR(20)  NOT NULL,
    nivel_resultante VARCHAR(10)  NOT NULL,
    dimension_id     INT                                      -- NULL = aplica al promedio global
                         REFERENCES dimensiones_evaluacion(id) ON DELETE SET NULL
                         DEFERRABLE INITIALLY IMMEDIATE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_config_tipo_alerta      CHECK (tipo_alerta      IN ('PREVENTIVA', 'MODERADA', 'CRITICA')),
    CONSTRAINT chk_config_nivel_resultante CHECK (nivel_resultante IN ('BAJO', 'MEDIO', 'ALTO'))
);

-- Índice para acelerar búsquedas de configuraciones de alerta por dimensión.
CREATE INDEX idx_config_alerta_dimension ON configuracion_alertas (dimension_id);

COMMENT ON TABLE  configuracion_alertas              IS 'Reglas del motor de alertas tempranas con rangos de umbral.';
COMMENT ON COLUMN configuracion_alertas.dimension_id IS 'NULL = regla aplica al promedio global del estudiante.';


-- ============================================================
-- 17. EVALUACIONES  (cabecera) -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de las cabeceras de evaluación que vinculan estudiante, docente y período.
CREATE TABLE evaluaciones (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id        INT          NOT NULL
                             REFERENCES estudiantes(id)  ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    periodo_id           INT          NOT NULL
                             REFERENCES periodos(id)     ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    usuario_id           INT          NOT NULL
                             REFERENCES usuarios(id)     ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    seccion_id           INT          NOT NULL               -- denormalizado para reporting por sección/nivel
                             REFERENCES secciones(id)    ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    observacion_general  TEXT,
    origen_registro      VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_evaluacion       UNIQUE (estudiante_id, usuario_id, periodo_id),
    CONSTRAINT chk_origen_registro CHECK  (origen_registro IN ('MANUAL', 'AUTOMATICO'))
);

-- Índice para acelerar el patrón de consulta más frecuente: evaluaciones de un estudiante en un período.
CREATE INDEX idx_eval_est_per ON evaluaciones (estudiante_id, periodo_id);
-- Índice para acelerar búsquedas de evaluaciones por docente.
CREATE INDEX idx_eval_usuario ON evaluaciones (usuario_id);
-- Índice para acelerar búsquedas de evaluaciones por sección.
CREATE INDEX idx_eval_seccion ON evaluaciones (seccion_id);

COMMENT ON TABLE  evaluaciones            IS 'Cabecera de evaluación: enlaza estudiante, docente y período.';
COMMENT ON COLUMN evaluaciones.seccion_id IS 'Sección en el momento de la evaluación. Denormalizado desde matriculas para preservar el contexto histórico.';


-- ============================================================
-- 18. DETALLE DE EVALUACIÓN  (una fila por criterio evaluado) -- DATOS FLEXIBLES
-- ============================================================
-- Tabla con los resultados de cada evaluación: criterio observado y escala de valoración asignada.
CREATE TABLE detalle_evaluacion (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id INT          NOT NULL
                      REFERENCES evaluaciones(id)          ON DELETE CASCADE
                      DEFERRABLE INITIALLY IMMEDIATE,
    criterio_id   INT          NOT NULL
                      REFERENCES criterios_indicadores(id) ON DELETE RESTRICT
                      DEFERRABLE INITIALLY IMMEDIATE,
    escala_id     INT          NOT NULL
                      REFERENCES escalas_valoracion(id)    ON DELETE RESTRICT
                      DEFERRABLE INITIALLY IMMEDIATE,
    observacion   TEXT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_detalle_criterio UNIQUE (evaluacion_id, criterio_id)
);

-- Índice para acceder al detalle de criterios evaluados dentro de una evaluación.
CREATE INDEX idx_detalle_evaluacion ON detalle_evaluacion (evaluacion_id);
-- Índice para consultar en cuántas evaluaciones aparece un criterio específico.
CREATE INDEX idx_detalle_criterio   ON detalle_evaluacion (criterio_id);
-- Índice para consultar el uso de cada escala de valoración en las evaluaciones.
CREATE INDEX idx_detalle_escala     ON detalle_evaluacion (escala_id);

COMMENT ON TABLE detalle_evaluacion IS '3NF: solo criterio_id y escala_id. valor_numerico se obtiene via JOIN con escalas_valoracion.';


-- ============================================================
-- 19. ALERTAS -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de las alertas de riesgo académico generadas automática o manualmente.
CREATE TABLE alertas (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id    INT          NOT NULL
                         REFERENCES estudiantes(id)           ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    contenido_id     INT          NOT NULL
                         REFERENCES contenidos(id)            ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    periodo_id       INT          NOT NULL
                         REFERENCES periodos(id)              ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    config_alerta_id INT          NOT NULL
                         REFERENCES configuracion_alertas(id) ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    evaluacion_id    INT                                      -- NULL = alerta manual sin evaluación automática
                         REFERENCES evaluaciones(id)          ON DELETE SET NULL
                         DEFERRABLE INITIALLY IMMEDIATE,
    generada_por     INT
                         REFERENCES usuarios(id)              ON DELETE SET NULL
                         DEFERRABLE INITIALLY IMMEDIATE,
    tipo_alerta      VARCHAR(20)  NOT NULL,
    nivel_alerta     VARCHAR(10)  NOT NULL,
    motivo           TEXT         NOT NULL,
    estado           VARCHAR(15)  NOT NULL DEFAULT 'ACTIVA',
    fecha_generacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_resolucion TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_alerta_tipo       CHECK (tipo_alerta  IN ('PREVENTIVA', 'MODERADA', 'CRITICA')),
    CONSTRAINT chk_alerta_nivel      CHECK (nivel_alerta IN ('BAJO', 'MEDIO', 'ALTO')),
    CONSTRAINT chk_alerta_estado     CHECK (estado       IN ('ACTIVA', 'RESUELTA', 'DESCARTADA')),
    CONSTRAINT chk_alerta_resolucion CHECK (
        (estado = 'ACTIVA'     AND fecha_resolucion IS NULL)
        OR
        (estado IN ('RESUELTA', 'DESCARTADA') AND fecha_resolucion IS NOT NULL)
    )
);

-- Índice para acelerar búsquedas de alertas por estudiante.
CREATE INDEX idx_alertas_estudiante ON alertas (estudiante_id);
-- Índice para acelerar búsquedas de alertas por período.
CREATE INDEX idx_alertas_periodo    ON alertas (periodo_id);
-- Índice para acelerar consultas que filtran alertas por estado.
CREATE INDEX idx_alertas_estado     ON alertas (estado);
-- Índice para acelerar consultas que ordenan alertas por fecha de generación.
CREATE INDEX idx_alertas_fecha      ON alertas (fecha_generacion DESC);
-- Índice para vincular alertas con la evaluación que las originó.
CREATE INDEX idx_alertas_evaluacion ON alertas (evaluacion_id);

COMMENT ON TABLE  alertas               IS 'Alertas de riesgo académico, manuales o generadas por el motor de reglas.';
COMMENT ON COLUMN alertas.evaluacion_id IS 'NULL para alertas manuales. Permite trazar qué evaluación originó la alerta.';


-- ============================================================
-- 20. TOKENS DE REFRESCO  (gestión JWT) -- DATOS FLEXIBLES
--
--  Spring Security con JWT necesita poder invalidar tokens
--  (logout, sesión expirada, incidente de seguridad).
--  Se almacena el HASH SHA-256 del token, nunca el token en claro.
-- ============================================================
-- Tabla de los tokens de refresco JWT para gestión de sesiones de usuarios.
CREATE TABLE tokens_refresh (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INT                      NOT NULL
                    REFERENCES usuarios(id) ON DELETE CASCADE
                    DEFERRABLE INITIALLY IMMEDIATE,
    token_hash  VARCHAR(255)             NOT NULL UNIQUE,   -- SHA-256 del token (no el token en claro)
    expira_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    revocado    BOOLEAN                  NOT NULL DEFAULT FALSE,
    revocado_en TIMESTAMP WITH TIME ZONE,
    ip_origen   INET,
    user_agent  VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_token_revocacion CHECK (
        (revocado = FALSE AND revocado_en IS NULL)
        OR
        (revocado = TRUE  AND revocado_en IS NOT NULL)
    )
);

-- Índice para acelerar búsquedas de tokens por usuario.
CREATE INDEX idx_token_usuario  ON tokens_refresh (usuario_id);
-- Índice para la validación rápida de tokens por su hash SHA-256.
CREATE INDEX idx_token_hash     ON tokens_refresh (token_hash);
-- Índice para identificar y limpiar tokens expirados.
CREATE INDEX idx_token_expira   ON tokens_refresh (expira_en);
-- Índice parcial para optimizar la validación de tokens aún vigentes (no revocados).
CREATE INDEX idx_token_vigentes ON tokens_refresh (usuario_id, expira_en)
    WHERE revocado = FALSE;

COMMENT ON TABLE  tokens_refresh            IS 'Tokens de refresco JWT. Almacena hash SHA-256 para poder invalidarlos.';
COMMENT ON COLUMN tokens_refresh.token_hash IS 'SHA-256 del refresh token. Nunca almacenar el token en claro.';


-- ============================================================
-- 21. REGISTRO DE AUDITORÍA -- DATOS FLEXIBLES
-- ============================================================
-- Tabla de auditoría que registra cada acción realizada en el sistema por los usuarios.
CREATE TABLE registro_auditoria (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         INT
                           REFERENCES usuarios(id) ON DELETE SET NULL
                           DEFERRABLE INITIALLY IMMEDIATE,
    accion             VARCHAR(50)  NOT NULL,   -- INSERT, UPDATE, DELETE, LOGIN, LOGOUT, VIEW, EXPORT
    tabla_nombre       VARCHAR(100),
    registro_id        BIGINT,                  -- BIGINT para soportar futuros cambios de PK
    valores_anteriores JSONB,
    valores_nuevos     JSONB,
    ip_origen          INET,
    user_agent         VARCHAR(500),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Índice para consultar el historial de acciones de un usuario específico.
CREATE INDEX idx_audit_usuario ON registro_auditoria (usuario_id);
-- Índice para consultar el historial de cambios sobre una tabla específica.
CREATE INDEX idx_audit_tabla   ON registro_auditoria (tabla_nombre);
-- Índice para filtrar el registro de auditoría por tipo de acción.
CREATE INDEX idx_audit_accion  ON registro_auditoria (accion);
-- Índice para consultar el registro de auditoría en orden cronológico descendente.
CREATE INDEX idx_audit_fecha   ON registro_auditoria (created_at DESC);

COMMENT ON TABLE  registro_auditoria             IS 'Log inmutable de acciones de usuario para seguridad y cumplimiento.';
COMMENT ON COLUMN registro_auditoria.registro_id IS 'BIGINT para soportar PKs de cualquier tipo sin migración futura.';


-- ============================================================
-- FUNCIÓN Y TRIGGERS — AUTO-UPDATE de updated_at
-- ============================================================

-- Función que actualiza automáticamente el campo updated_at con la fecha y hora actual antes de cada modificación.
CREATE OR REPLACE FUNCTION fn_actualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_actualizar_updated_at IS 'Asigna updated_at = NOW() antes de cada UPDATE.';

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en anios_lectivos.
CREATE TRIGGER trg_anios_lectivos_upd
    BEFORE UPDATE ON anios_lectivos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en periodos.
CREATE TRIGGER trg_periodos_upd
    BEFORE UPDATE ON periodos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en centros_educativos.
CREATE TRIGGER trg_centros_educativos_upd
    BEFORE UPDATE ON centros_educativos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en materias.
CREATE TRIGGER trg_materias_upd
    BEFORE UPDATE ON materias
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en dimensiones_evaluacion.
CREATE TRIGGER trg_dimensiones_upd
    BEFORE UPDATE ON dimensiones_evaluacion
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en usuarios.
CREATE TRIGGER trg_usuarios_upd
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en secciones.
CREATE TRIGGER trg_secciones_upd
    BEFORE UPDATE ON secciones
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en estudiantes.
CREATE TRIGGER trg_estudiantes_upd
    BEFORE UPDATE ON estudiantes
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en matriculas.
CREATE TRIGGER trg_matriculas_upd
    BEFORE UPDATE ON matriculas
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en contenidos.
CREATE TRIGGER trg_contenidos_upd
    BEFORE UPDATE ON contenidos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en criterios_indicadores.
CREATE TRIGGER trg_criterios_upd
    BEFORE UPDATE ON criterios_indicadores
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en configuracion_alertas.
CREATE TRIGGER trg_config_alertas_upd
    BEFORE UPDATE ON configuracion_alertas
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en evaluaciones.
CREATE TRIGGER trg_evaluaciones_upd
    BEFORE UPDATE ON evaluaciones
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

-- Trigger que ejecuta fn_actualizar_updated_at antes de cada actualización en alertas.
CREATE TRIGGER trg_alertas_upd
    BEFORE UPDATE ON alertas
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();
