-- ============================================================
-- ATARA — Sistema Web de Alertas Tempranas y Análisis del
--         Rendimiento Académico
--
-- Base de datos : PostgreSQL 15+
-- Esquema       : public
-- Versión       : V1 (Flyway)
-- Codificación  : UTF-8
--
-- ORDEN DE TABLAS (respeta dependencias FK):
--   1.  roles
--   2.  anios_lectivos         (+ updated_at, UNIQUE parcial activo)
--   3.  niveles
--   4.  escalas_valoracion
--   5.  dimensiones_evaluacion (+ updated_at) — antes que criterios_indicadores
--   6.  centros_educativos     (+ updated_at)
--   7.  materias               (+ updated_at)
--   8.  periodos               (+ updated_at, UNIQUE parcial activo por anio)
--   9.  usuarios               (+ apellidos, estado, ultimo_acceso, updated_at)
--  10.  secciones              (nivel_id FK en lugar de nivel VARCHAR, updated_at)
--  11.  usuarios_secciones     (M:N docente-seccion)
--  12.  estudiantes            (+ genero, acudiente, estado, updated_at)
--  13.  contenidos             (+ updated_at, UNIQUE por materia)
--  14.  criterios_indicadores  (+ peso, updated_at, dimension_id nullable)
--  15.  configuracion_alertas  (+ dimension_id FK nullable, updated_at)
--  16.  evaluaciones           (+ seccion_id denormalizado, UNIQUE, updated_at)
--  17.  detalle_evaluacion     (solo criterio_id + escala_id — 3NF)
--  18.  alertas                (+ evaluacion_id FK nullable, generada_por, updated_at)
--  19.  tokens_refresh         (gestión JWT — almacena hash SHA-256)
--  20.  registro_auditoria     (registro_id BIGINT, JSONB antes/después)
--
-- NOTA: Este script incorpora todas las correcciones que en
--       versiones anteriores del proyecto vivían en V4.
--       V4__corrections.sql es un no-op comentado.
-- ============================================================


-- ============================================================
-- 1. ROLES
-- ============================================================
CREATE TABLE roles (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(50)  NOT NULL
                    CONSTRAINT uq_rol_nombre UNIQUE,
    descripcion TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE roles IS 'Catálogo de roles del sistema: ADMIN, DOCENTE, COORDINADOR.';


-- ============================================================
-- 2. AÑOS LECTIVOS
-- ============================================================
CREATE TABLE anios_lectivos (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio        SMALLINT    NOT NULL
                    CONSTRAINT uq_anio_lectivo UNIQUE,
    fecha_inicio DATE        NOT NULL,
    fecha_fin    DATE        NOT NULL,
    activo       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_anio_rango   CHECK (anio BETWEEN 2000 AND 2100),
    CONSTRAINT chk_anio_fechas  CHECK (fecha_fin > fecha_inicio)
);

-- Solo puede existir UN año lectivo activo a la vez
CREATE UNIQUE INDEX uq_un_anio_activo
    ON anios_lectivos (activo)
    WHERE activo = TRUE;

-- Consultas frecuentes de "año lectivo activo"
CREATE INDEX idx_anios_activo ON anios_lectivos (activo);

COMMENT ON TABLE  anios_lectivos        IS 'Año escolar (ej. 2025). Solo uno puede estar activo.';
COMMENT ON COLUMN anios_lectivos.activo IS 'TRUE = año en curso. Índice parcial garantiza unicidad.';


-- ============================================================
-- 3. NIVELES ACADÉMICOS  (1° – 6° primaria)
-- ============================================================
CREATE TABLE niveles (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_grado   SMALLINT    NOT NULL
                       CONSTRAINT uq_nivel_grado UNIQUE,
    nombre         VARCHAR(100) NOT NULL
                       CONSTRAINT uq_nivel_nombre UNIQUE,
    descripcion    TEXT,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_grado_rango CHECK (numero_grado BETWEEN 1 AND 6)
);

COMMENT ON TABLE  niveles             IS 'Catálogo fijo: grados 1° a 6° de educación primaria.';
COMMENT ON COLUMN niveles.numero_grado IS '1 = Primer Grado … 6 = Sexto Grado.';


-- ============================================================
-- 4. ESCALAS DE VALORACIÓN  (Likert 1-4)
-- ============================================================
CREATE TABLE escalas_valoracion (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(50)  NOT NULL
                        CONSTRAINT uq_escala_nombre UNIQUE,
    etiqueta        CHAR(1)      NOT NULL
                        CONSTRAINT uq_escala_etiqueta UNIQUE,
    valor_numerico  SMALLINT     NOT NULL
                        CONSTRAINT uq_escala_valor UNIQUE,
    descripcion     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_escala_valor CHECK (valor_numerico BETWEEN 1 AND 4)
);

COMMENT ON TABLE  escalas_valoracion                IS 'Escala Likert 1-4: I, B, S, D.';
COMMENT ON COLUMN escalas_valoracion.valor_numerico IS '1=Insuficiente 2=Básico 3=Satisfactorio 4=Destacado';


-- ============================================================
-- 5. DIMENSIONES DE EVALUACIÓN
--    Se crea ANTES que criterios_indicadores y configuracion_alertas
--    porque ambas tablas referencian dimension_id.
-- ============================================================
CREATE TABLE dimensiones_evaluacion (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(150) NOT NULL
                    CONSTRAINT uq_dimension_nombre UNIQUE,
    descripcion TEXT,
    peso        NUMERIC(5,2) NOT NULL DEFAULT 1.0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_dimension_peso CHECK (peso > 0)
);

COMMENT ON TABLE  dimensiones_evaluacion       IS 'Ejes de evaluación: Rendimiento Académico, Participación, Hábitos, Socioemocional, Asistencia.';
COMMENT ON COLUMN dimensiones_evaluacion.peso  IS 'Peso relativo al calcular promedios ponderados.';


-- ============================================================
-- 6. CENTROS EDUCATIVOS
-- ============================================================
CREATE TABLE centros_educativos (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(200) NOT NULL
                            CONSTRAINT uq_centro_nombre UNIQUE,
    circuito            VARCHAR(10),
    direccion_regional  VARCHAR(100),
    telefono            VARCHAR(20),
    correo              VARCHAR(150),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE centros_educativos IS 'Escuelas primarias registradas en el sistema.';


-- ============================================================
-- 7. MATERIAS
-- ============================================================
CREATE TABLE materias (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(100) NOT NULL
                    CONSTRAINT uq_materia_nombre UNIQUE,
    descripcion TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE materias IS 'Áreas curriculares: Matemáticas, Español, Ciencias, etc.';


-- ============================================================
-- 8. PERÍODOS  (ventanas de evaluación bimensuales)
-- ============================================================
CREATE TABLE periodos (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio_lectivo_id INT         NOT NULL
                        REFERENCES anios_lectivos(id) ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    nombre          VARCHAR(100) NOT NULL,
    numero_periodo  SMALLINT    NOT NULL,
    fecha_inicio    DATE        NOT NULL,
    fecha_fin       DATE        NOT NULL,
    activo          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_periodo_por_anio   UNIQUE (anio_lectivo_id, numero_periodo),
    CONSTRAINT chk_periodo_numero    CHECK  (numero_periodo BETWEEN 1 AND 6),
    CONSTRAINT chk_periodo_fechas    CHECK  (fecha_fin > fecha_inicio)
);

-- Solo puede existir UN período activo por año lectivo
CREATE UNIQUE INDEX uq_periodo_activo_por_anio
    ON periodos (anio_lectivo_id)
    WHERE activo = TRUE;

CREATE INDEX idx_periodos_anio   ON periodos (anio_lectivo_id);
CREATE INDEX idx_periodos_activo ON periodos (activo);

COMMENT ON TABLE  periodos        IS 'Períodos bimensuales de evaluación dentro de un año lectivo.';
COMMENT ON COLUMN periodos.activo IS 'TRUE = período de evaluación en curso. Índice parcial garantiza unicidad por año.';


-- ============================================================
-- 9. USUARIOS
-- ============================================================
CREATE TABLE usuarios (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100) NOT NULL,
    apellidos     VARCHAR(150) NOT NULL,
    correo        VARCHAR(150) NOT NULL
                      CONSTRAINT uq_usuario_correo UNIQUE,
    password      VARCHAR(255) NOT NULL,   -- BCrypt 60 chars — nunca texto plano
    rol_id        INT         NOT NULL
                      REFERENCES roles(id) ON DELETE RESTRICT
                      DEFERRABLE INITIALLY IMMEDIATE,
    estado        VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    ultimo_acceso TIMESTAMP WITH TIME ZONE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_usuario_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE INDEX idx_usuarios_rol    ON usuarios (rol_id);
CREATE INDEX idx_usuarios_estado ON usuarios (estado);

COMMENT ON TABLE  usuarios          IS 'Usuarios del sistema: ADMIN, DOCENTE y COORDINADOR.';
COMMENT ON COLUMN usuarios.password IS 'Hash BCrypt (exactamente 60 caracteres). Ver ACCIÓN REQUERIDA en README.';


-- ============================================================
-- 10. SECCIONES
-- ============================================================
CREATE TABLE secciones (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(10)  NOT NULL,   -- 'A', 'B', 'C', …
    nivel_id        INT          NOT NULL
                        REFERENCES niveles(id)          ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    centro_id       INT          NOT NULL
                        REFERENCES centros_educativos(id) ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    anio_lectivo_id INT          NOT NULL
                        REFERENCES anios_lectivos(id)   ON DELETE RESTRICT
                        DEFERRABLE INITIALLY IMMEDIATE,
    docente_id      INT
                        REFERENCES usuarios(id)         ON DELETE SET NULL
                        DEFERRABLE INITIALLY IMMEDIATE,
    capacidad       SMALLINT     CHECK (capacidad > 0),
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_seccion UNIQUE (nivel_id, centro_id, anio_lectivo_id, nombre)
);

CREATE INDEX idx_secciones_nivel   ON secciones (nivel_id);
CREATE INDEX idx_secciones_centro  ON secciones (centro_id);
CREATE INDEX idx_secciones_anio    ON secciones (anio_lectivo_id);
CREATE INDEX idx_secciones_docente ON secciones (docente_id);

COMMENT ON TABLE  secciones           IS 'Grupo-aula: combinación única de nivel, centro, año lectivo y letra.';
COMMENT ON COLUMN secciones.docente_id IS 'Docente titular. Otros docentes asignados via usuarios_secciones.';


-- ============================================================
-- 11. USUARIOS ↔ SECCIONES  (M:N)
-- ============================================================
CREATE TABLE usuarios_secciones (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INT NOT NULL
                    REFERENCES usuarios(id)  ON DELETE CASCADE
                    DEFERRABLE INITIALLY IMMEDIATE,
    seccion_id  INT NOT NULL
                    REFERENCES secciones(id) ON DELETE CASCADE
                    DEFERRABLE INITIALLY IMMEDIATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_usuario_seccion UNIQUE (usuario_id, seccion_id)
);

CREATE INDEX idx_us_usuario  ON usuarios_secciones (usuario_id);
CREATE INDEX idx_us_seccion  ON usuarios_secciones (seccion_id);

COMMENT ON TABLE usuarios_secciones IS 'Docentes (o coordinadores) asignados a una o más secciones.';


-- ============================================================
-- 12. ESTUDIANTES
-- ============================================================
CREATE TABLE estudiantes (
    id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificacion      VARCHAR(20)  UNIQUE,   -- código institucional o cédula de identidad
    nombre              VARCHAR(100) NOT NULL,
    apellido1           VARCHAR(100) NOT NULL,
    apellido2           VARCHAR(100),
    fecha_nacimiento    DATE,
    genero              CHAR(1)      CHECK (genero IN ('M', 'F', 'O')),
    seccion_id          INT          NOT NULL
                            REFERENCES secciones(id) ON DELETE RESTRICT
                            DEFERRABLE INITIALLY IMMEDIATE,
    nombre_acudiente    VARCHAR(200),
    telefono_acudiente  VARCHAR(20),
    correo_acudiente    VARCHAR(150),
    estado              VARCHAR(10)  NOT NULL DEFAULT 'ACTIVO',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_estudiante_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'TRASLADADO'))
);

CREATE INDEX idx_estudiantes_seccion    ON estudiantes (seccion_id);
CREATE INDEX idx_estudiantes_estado     ON estudiantes (estado);
CREATE INDEX idx_estudiantes_apellido1  ON estudiantes (apellido1, nombre);

COMMENT ON TABLE  estudiantes                IS 'Estudiantes de primaria matriculados en una sección.';
COMMENT ON COLUMN estudiantes.identificacion IS 'Opcional; debe ser único cuando se proporciona.';


-- ============================================================
-- 13. CONTENIDOS
-- ============================================================
CREATE TABLE contenidos (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR(200) NOT NULL,
    descripcion TEXT,
    materia_id  INT          NOT NULL
                    REFERENCES materias(id) ON DELETE RESTRICT
                    DEFERRABLE INITIALLY IMMEDIATE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_contenido_por_materia UNIQUE (materia_id, nombre)
);

CREATE INDEX idx_contenidos_materia ON contenidos (materia_id);

COMMENT ON TABLE contenidos IS 'Unidades temáticas dentro de cada materia.';


-- ============================================================
-- 14. CRITERIOS / INDICADORES
-- ============================================================
CREATE TABLE criterios_indicadores (
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(200) NOT NULL,
    descripcion  TEXT,
    contenido_id INT          NOT NULL
                     REFERENCES contenidos(id)           ON DELETE RESTRICT
                     DEFERRABLE INITIALLY IMMEDIATE,
    dimension_id INT                                     -- NULL = criterio transversal
                     REFERENCES dimensiones_evaluacion(id) ON DELETE SET NULL
                     DEFERRABLE INITIALLY IMMEDIATE,
    peso         NUMERIC(5,2) NOT NULL DEFAULT 1.0,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_criterio_por_contenido UNIQUE (contenido_id, nombre),
    CONSTRAINT chk_criterio_peso         CHECK  (peso > 0)
);

CREATE INDEX idx_criterios_contenido  ON criterios_indicadores (contenido_id);
CREATE INDEX idx_criterios_dimension  ON criterios_indicadores (dimension_id);

COMMENT ON TABLE  criterios_indicadores             IS 'Ítems observables evaluados con escala Likert 1-4.';
COMMENT ON COLUMN criterios_indicadores.dimension_id IS 'NULL para criterios transversales (ej. asistencia).';


-- ============================================================
-- 15. CONFIGURACIÓN DE ALERTAS  (motor de reglas)
-- ============================================================
CREATE TABLE configuracion_alertas (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre           VARCHAR(200) NOT NULL,
    descripcion      TEXT,
    umbral_minimo    NUMERIC(5,2),
    umbral_maximo    NUMERIC(5,2),
    tipo_alerta      VARCHAR(20)  NOT NULL,
    nivel_resultante VARCHAR(10)  NOT NULL,
    dimension_id     INT                                      -- NULL = aplica al promedio global
                         REFERENCES dimensiones_evaluacion(id) ON DELETE SET NULL
                         DEFERRABLE INITIALLY IMMEDIATE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_config_tipo_alerta      CHECK (tipo_alerta      IN ('PREVENTIVA', 'MODERADA', 'CRITICA')),
    CONSTRAINT chk_config_nivel_resultante CHECK (nivel_resultante IN ('BAJO', 'MEDIO', 'ALTO'))
);

CREATE INDEX idx_config_alerta_dimension ON configuracion_alertas (dimension_id);

COMMENT ON TABLE  configuracion_alertas             IS 'Reglas del motor de alertas tempranas con rangos de umbral.';
COMMENT ON COLUMN configuracion_alertas.dimension_id IS 'NULL = regla aplica al promedio global del estudiante.';


-- ============================================================
-- 16. EVALUACIONES  (cabecera)
-- ============================================================
CREATE TABLE evaluaciones (
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id        INT          NOT NULL
                             REFERENCES estudiantes(id)  ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    periodo_id           INT          NOT NULL
                             REFERENCES periodos(id)     ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    usuario_id           INT          NOT NULL
                             REFERENCES usuarios(id)     ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    seccion_id           INT          NOT NULL               -- denormalizado para reporting por sección/nivel
                             REFERENCES secciones(id)    ON DELETE RESTRICT
                             DEFERRABLE INITIALLY IMMEDIATE,
    observacion_general  TEXT,
    origen_registro      VARCHAR(20)  NOT NULL DEFAULT 'MANUAL',
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_evaluacion         UNIQUE (estudiante_id, usuario_id, periodo_id),
    CONSTRAINT chk_origen_registro   CHECK  (origen_registro IN ('MANUAL', 'AUTOMATICO'))
);

-- Patrón de consulta más frecuente: evaluaciones de un estudiante en un período
CREATE INDEX idx_eval_est_per      ON evaluaciones (estudiante_id, periodo_id);
CREATE INDEX idx_eval_usuario      ON evaluaciones (usuario_id);
CREATE INDEX idx_eval_seccion      ON evaluaciones (seccion_id);

COMMENT ON TABLE  evaluaciones            IS 'Cabecera de evaluación: enlaza estudiante, docente y período.';
COMMENT ON COLUMN evaluaciones.seccion_id IS 'Sección en el momento de la evaluación (no la actual del estudiante).';


-- ============================================================
-- 17. DETALLE DE EVALUACIÓN  (una fila por criterio evaluado)
-- ============================================================
CREATE TABLE detalle_evaluacion (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_id INT          NOT NULL
                      REFERENCES evaluaciones(id)         ON DELETE CASCADE
                      DEFERRABLE INITIALLY IMMEDIATE,
    criterio_id   INT          NOT NULL
                      REFERENCES criterios_indicadores(id) ON DELETE RESTRICT
                      DEFERRABLE INITIALLY IMMEDIATE,
    escala_id     INT          NOT NULL
                      REFERENCES escalas_valoracion(id)   ON DELETE RESTRICT
                      DEFERRABLE INITIALLY IMMEDIATE,
    observacion   TEXT,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_detalle_criterio UNIQUE (evaluacion_id, criterio_id)
);

CREATE INDEX idx_detalle_evaluacion ON detalle_evaluacion (evaluacion_id);
CREATE INDEX idx_detalle_criterio   ON detalle_evaluacion (criterio_id);
CREATE INDEX idx_detalle_escala     ON detalle_evaluacion (escala_id);

COMMENT ON TABLE detalle_evaluacion IS '3NF: solo criterio_id y escala_id. valor_numerico se obtiene via JOIN con escalas_valoracion.';


-- ============================================================
-- 18. ALERTAS
-- ============================================================
CREATE TABLE alertas (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id    INT          NOT NULL
                         REFERENCES estudiantes(id)        ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    contenido_id     INT          NOT NULL
                         REFERENCES contenidos(id)         ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    periodo_id       INT          NOT NULL
                         REFERENCES periodos(id)           ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    config_alerta_id INT          NOT NULL
                         REFERENCES configuracion_alertas(id) ON DELETE RESTRICT
                         DEFERRABLE INITIALLY IMMEDIATE,
    evaluacion_id    INT                                   -- NULL = alerta manual sin evaluación automática
                         REFERENCES evaluaciones(id)       ON DELETE SET NULL
                         DEFERRABLE INITIALLY IMMEDIATE,
    generada_por     INT
                         REFERENCES usuarios(id)           ON DELETE SET NULL
                         DEFERRABLE INITIALLY IMMEDIATE,
    tipo_alerta      VARCHAR(20)  NOT NULL,
    nivel_alerta     VARCHAR(10)  NOT NULL,
    motivo           TEXT         NOT NULL,
    estado           VARCHAR(15)  NOT NULL DEFAULT 'ACTIVA',
    fecha_generacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_resolucion TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_alerta_tipo    CHECK (tipo_alerta  IN ('PREVENTIVA', 'MODERADA', 'CRITICA')),
    CONSTRAINT chk_alerta_nivel   CHECK (nivel_alerta IN ('BAJO', 'MEDIO', 'ALTO')),
    CONSTRAINT chk_alerta_estado  CHECK (estado       IN ('ACTIVA', 'RESUELTA', 'DESCARTADA')),
    CONSTRAINT chk_alerta_resolucion CHECK (
        (estado = 'ACTIVA'     AND fecha_resolucion IS NULL)
        OR
        (estado IN ('RESUELTA', 'DESCARTADA') AND fecha_resolucion IS NOT NULL)
    )
);

CREATE INDEX idx_alertas_estudiante  ON alertas (estudiante_id);
CREATE INDEX idx_alertas_periodo     ON alertas (periodo_id);
CREATE INDEX idx_alertas_estado      ON alertas (estado);
CREATE INDEX idx_alertas_fecha       ON alertas (fecha_generacion DESC);
CREATE INDEX idx_alertas_evaluacion  ON alertas (evaluacion_id);

COMMENT ON TABLE  alertas              IS 'Alertas de riesgo académico, manuales o generadas por el motor de reglas.';
COMMENT ON COLUMN alertas.evaluacion_id IS 'NULL para alertas manuales. Permite trazar qué evaluación originó la alerta.';


-- ============================================================
-- 19. TOKENS DE REFRESCO  (gestión JWT)
--
--  Spring Security con JWT necesita poder invalidar tokens
--  (logout, sesión expirada, incidente de seguridad).
--  Se almacena el HASH SHA-256 del token, nunca el token en claro.
-- ============================================================
CREATE TABLE tokens_refresh (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  INT                      NOT NULL
                    REFERENCES usuarios(id) ON DELETE CASCADE
                    DEFERRABLE INITIALLY IMMEDIATE,
    token_hash  VARCHAR(255)             NOT NULL UNIQUE,   -- SHA-256 del token (no el token en claro)
    expira_en   TIMESTAMP WITH TIME ZONE NOT NULL,
    revocado    BOOLEAN                  NOT NULL DEFAULT FALSE,
    revocado_en TIMESTAMP WITH TIME ZONE,
    ip_origen   INET,
    user_agent  VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_token_revocacion CHECK (
        (revocado = FALSE AND revocado_en IS NULL)
        OR
        (revocado = TRUE  AND revocado_en IS NOT NULL)
    )
);

CREATE INDEX idx_token_usuario   ON tokens_refresh (usuario_id);
CREATE INDEX idx_token_hash      ON tokens_refresh (token_hash);
CREATE INDEX idx_token_expira    ON tokens_refresh (expira_en);
-- Índice parcial: solo tokens vigentes (los más consultados en validación)
CREATE INDEX idx_token_vigentes  ON tokens_refresh (usuario_id, expira_en)
    WHERE revocado = FALSE;

COMMENT ON TABLE  tokens_refresh           IS 'Tokens de refresco JWT. Almacena hash SHA-256 para poder invalidarlos.';
COMMENT ON COLUMN tokens_refresh.token_hash IS 'SHA-256 del refresh token. Nunca almacenar el token en claro.';


-- ============================================================
-- 20. REGISTRO DE AUDITORÍA
-- ============================================================
CREATE TABLE registro_auditoria (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         INT
                           REFERENCES usuarios(id) ON DELETE SET NULL
                           DEFERRABLE INITIALLY IMMEDIATE,
    accion             VARCHAR(50)  NOT NULL,   -- INSERT, UPDATE, DELETE, LOGIN, LOGOUT, VIEW, EXPORT
    tabla_nombre       VARCHAR(100),
    registro_id        BIGINT,                  -- BIGINT para soportar futuros cambios de PK
    valores_anteriores JSONB,
    valores_nuevos     JSONB,
    ip_origen          INET,
    user_agent         VARCHAR(500),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_usuario  ON registro_auditoria (usuario_id);
CREATE INDEX idx_audit_tabla    ON registro_auditoria (tabla_nombre);
CREATE INDEX idx_audit_accion   ON registro_auditoria (accion);
CREATE INDEX idx_audit_fecha    ON registro_auditoria (created_at DESC);

COMMENT ON TABLE  registro_auditoria            IS 'Log inmutable de acciones de usuario para seguridad y cumplimiento.';
COMMENT ON COLUMN registro_auditoria.registro_id IS 'BIGINT para soportar PKs de cualquier tipo sin migración futura.';


-- ============================================================
-- FUNCIÓN Y TRIGGERS — AUTO-UPDATE de updated_at
-- ============================================================

CREATE OR REPLACE FUNCTION fn_actualizar_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION fn_actualizar_updated_at IS 'Asigna updated_at = NOW() antes de cada UPDATE.';

CREATE TRIGGER trg_anios_lectivos_upd
    BEFORE UPDATE ON anios_lectivos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_periodos_upd
    BEFORE UPDATE ON periodos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_centros_educativos_upd
    BEFORE UPDATE ON centros_educativos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_materias_upd
    BEFORE UPDATE ON materias
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_dimensiones_upd
    BEFORE UPDATE ON dimensiones_evaluacion
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_usuarios_upd
    BEFORE UPDATE ON usuarios
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_secciones_upd
    BEFORE UPDATE ON secciones
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_estudiantes_upd
    BEFORE UPDATE ON estudiantes
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_contenidos_upd
    BEFORE UPDATE ON contenidos
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_criterios_upd
    BEFORE UPDATE ON criterios_indicadores
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_config_alertas_upd
    BEFORE UPDATE ON configuracion_alertas
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_evaluaciones_upd
    BEFORE UPDATE ON evaluaciones
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();

CREATE TRIGGER trg_alertas_upd
    BEFORE UPDATE ON alertas
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_updated_at();
