-- ============================================================
-- ATARA — Evaluación por Saberes y Alertas Temáticas
--
-- Version : V4
--
-- Nuevas tablas:
--   1. tipos_saber            (3 registros: Conceptual, Procedimental, Actitudinal)
--   2. ejes_tematicos         (7 por tipo de saber = 21 total)
--   3. niveles_desempeno      (escala 1-5)
--   4. evaluaciones_saber     (cabecera: estudiante + periodo + usuario + fecha)
--   5. detalle_evaluacion_saber (valor por eje temático)
--   6. alertas_tematicas      (generadas por promedios de ejes por periodo)
-- ============================================================

-- ============================================================
-- 1. TIPOS DE SABER
-- ============================================================
CREATE TABLE tipos_saber (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    clave       VARCHAR(20) NOT NULL
                    CONSTRAINT uq_tipo_saber_clave UNIQUE,
    nombre      VARCHAR(100) NOT NULL
                    CONSTRAINT uq_tipo_saber_nombre UNIQUE,
    descripcion TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE tipos_saber IS 'Catálogo de tipos de saber: Conceptual, Procedimental, Actitudinal.';

INSERT INTO tipos_saber (clave, nombre, descripcion) VALUES
('CONCEPTUAL',    'Saber Conceptual',    'Conocimientos teóricos: qué saber, conceptos, hechos y principios'),
('PROCEDIMENTAL', 'Saber Procedimental', 'Habilidades prácticas: cómo hacer, técnicas, procedimientos y estrategias'),
('ACTITUDINAL',   'Saber Actitudinal',   'Disposiciones y valores: querer hacer, actitudes, motivación y compromiso');

-- ============================================================
-- 2. EJES TEMÁTICOS (7 por tipo de saber = 21 total)
-- ============================================================
CREATE TABLE ejes_tematicos (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_saber_id   INT NOT NULL
                        REFERENCES tipos_saber(id) ON DELETE RESTRICT,
    clave           VARCHAR(30) NOT NULL
                        CONSTRAINT uq_eje_clave UNIQUE,
    nombre          VARCHAR(150) NOT NULL,
    descripcion     TEXT,
    orden           SMALLINT NOT NULL DEFAULT 1,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_eje_por_tipo UNIQUE (tipo_saber_id, orden)
);

CREATE INDEX idx_ejes_tipo_saber ON ejes_tematicos(tipo_saber_id);

COMMENT ON TABLE ejes_tematicos IS 'Ejes temáticos de evaluación, 7 por cada tipo de saber (21 total).';

-- Ejes del Saber Conceptual (tipo_saber_id = 1)
INSERT INTO ejes_tematicos (tipo_saber_id, clave, nombre, descripcion, orden) VALUES
(1, 'C_FONOLOGICA',     'Conciencia fonológica y lectoescritura',       'Dominio de relaciones sonido-grafía y principios de lectoescritura',    1),
(1, 'C_COMPRENSION',    'Comprensión lectora conceptual',               'Identificación de ideas principales, estructuras y tipos de texto',     2),
(1, 'C_VOCABULARIO',    'Vocabulario y significado',                     'Conocimiento de familias de palabras, sinónimos, antónimos y campos semánticos', 3),
(1, 'C_GRAMATICA',      'Gramática y estructura lingüística',           'Dominio de categorías gramaticales, oración, concordancia y tiempos verbales', 4),
(1, 'C_PRODUCCION',     'Producción textual conceptual',                'Conocimiento de estructuras textuales, géneros y convenciones de escritura', 5),
(1, 'C_LITERATURA',     'Literatura y apreciación literaria',           'Conocimiento de géneros literarios, autores, figuras retóricas y contexto cultural', 6),
(1, 'C_EXPRESION_ORAL', 'Expresión oral y comunicación conceptual',     'Conocimiento de normas comunicativas, registros del habla y técnicas expositivas', 7);

-- Ejes del Saber Procedimental (tipo_saber_id = 2)
INSERT INTO ejes_tematicos (tipo_saber_id, clave, nombre, descripcion, orden) VALUES
(2, 'P_FONOLOGICA',     'Prácticas de lectoescritura',                  'Aplicación de estrategias de decodificación y escritura funcional',     1),
(2, 'P_COMPRENSION',    'Estrategias de comprensión lectora',           'Uso de predicción, inferencia, resumen y conexión texto-experiencia',   2),
(2, 'P_VOCABULARIO',    'Uso contextualizado del vocabulario',          'Aplicación de vocabulario nuevo en producción oral y escrita',          3),
(2, 'P_GRAMATICA',      'Aplicación gramatical en contexto',            'Uso correcto de estructuras gramaticales en producciones reales',       4),
(2, 'P_PRODUCCION',     'Producción textual aplicada',                  'Redacción de textos diversos con planificación, revisión y corrección', 5),
(2, 'P_LITERATURA',     'Interpretación y análisis literario',          'Análisis de textos literarios, comparación de obras y producción creativa', 6),
(2, 'P_EXPRESION_ORAL', 'Prácticas de expresión oral',                  'Participación en exposiciones, debates, dramatizaciones y diálogos',    7);

-- Ejes del Saber Actitudinal (tipo_saber_id = 3)
INSERT INTO ejes_tematicos (tipo_saber_id, clave, nombre, descripcion, orden) VALUES
(3, 'A_FONOLOGICA',     'Disposición hacia la lectoescritura',          'Interés y motivación por aprender a leer y escribir',                  1),
(3, 'A_COMPRENSION',    'Hábito y gusto por la lectura',               'Voluntad de leer, curiosidad lectora y perseverancia ante textos difíciles', 2),
(3, 'A_VOCABULARIO',    'Curiosidad léxica y precisión comunicativa',   'Interés por ampliar vocabulario y usarlo con precisión',                3),
(3, 'A_GRAMATICA',      'Valoración de la corrección lingüística',     'Actitud de cuidado y revisión en la expresión escrita y oral',          4),
(3, 'A_PRODUCCION',     'Compromiso con la producción textual',        'Responsabilidad, creatividad y esfuerzo en tareas de escritura',        5),
(3, 'A_LITERATURA',     'Sensibilidad y apreciación literaria',        'Disfrute de la lectura literaria, empatía con personajes y valoración cultural', 6),
(3, 'A_EXPRESION_ORAL', 'Participación y respeto comunicativo',        'Disposición a expresarse, escuchar activamente y respetar turnos de habla', 7);

-- ============================================================
-- 3. NIVELES DE DESEMPEÑO (escala 1-5)
-- ============================================================
CREATE TABLE niveles_desempeno (
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_numerico  SMALLINT NOT NULL
                        CONSTRAINT uq_ndesempeno_valor UNIQUE
                        CONSTRAINT chk_ndesempeno_rango CHECK (valor_numerico BETWEEN 1 AND 5),
    nombre          VARCHAR(50) NOT NULL
                        CONSTRAINT uq_ndesempeno_nombre UNIQUE,
    etiqueta        VARCHAR(5) NOT NULL
                        CONSTRAINT uq_ndesempeno_etiqueta UNIQUE,
    descripcion     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE niveles_desempeno IS 'Escala de valoración de 5 niveles para evaluaciones por saberes.';

INSERT INTO niveles_desempeno (valor_numerico, nombre, etiqueta, descripcion) VALUES
(1, 'Inicial',        'INI', 'No demuestra los aprendizajes esperados para el eje'),
(2, 'En desarrollo',  'DES', 'Muestra avances incipientes, requiere apoyo constante'),
(3, 'Intermedio',     'INT', 'Alcanza parcialmente los aprendizajes esperados'),
(4, 'Logrado',        'LOG', 'Alcanza los aprendizajes esperados de forma consistente'),
(5, 'Avanzado',       'AVA', 'Supera los aprendizajes esperados, demuestra dominio pleno');

-- ============================================================
-- 4. EVALUACIONES POR SABER (cabecera)
-- ============================================================
CREATE TABLE evaluaciones_saber (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id   BIGINT NOT NULL
                        REFERENCES estudiantes(id) ON DELETE RESTRICT,
    periodo_id      BIGINT NOT NULL
                        REFERENCES periodos(id) ON DELETE RESTRICT,
    usuario_id      BIGINT NOT NULL
                        REFERENCES usuarios(id) ON DELETE RESTRICT,
    seccion_id      BIGINT NOT NULL
                        REFERENCES secciones(id) ON DELETE RESTRICT,
    tipo_saber_id   INT NOT NULL
                        REFERENCES tipos_saber(id) ON DELETE RESTRICT,
    fecha_evaluacion DATE NOT NULL DEFAULT CURRENT_DATE,
    observacion     TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_eval_saber_estudiante   ON evaluaciones_saber(estudiante_id);
CREATE INDEX idx_eval_saber_periodo      ON evaluaciones_saber(periodo_id);
CREATE INDEX idx_eval_saber_seccion      ON evaluaciones_saber(seccion_id);
CREATE INDEX idx_eval_saber_tipo         ON evaluaciones_saber(tipo_saber_id);
CREATE INDEX idx_eval_saber_est_periodo  ON evaluaciones_saber(estudiante_id, periodo_id);

COMMENT ON TABLE evaluaciones_saber IS 'Cabecera de evaluación por tipo de saber. Permite múltiples evaluaciones por estudiante/periodo/tipo.';

-- Trigger updated_at
CREATE OR REPLACE FUNCTION fn_eval_saber_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_eval_saber_updated_at
    BEFORE UPDATE ON evaluaciones_saber
    FOR EACH ROW EXECUTE FUNCTION fn_eval_saber_updated_at();

-- ============================================================
-- 5. DETALLE DE EVALUACIÓN POR SABER (valor por eje temático)
-- ============================================================
CREATE TABLE detalle_evaluacion_saber (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluacion_saber_id BIGINT NOT NULL
                            REFERENCES evaluaciones_saber(id) ON DELETE CASCADE,
    eje_tematico_id     INT NOT NULL
                            REFERENCES ejes_tematicos(id) ON DELETE RESTRICT,
    valor               SMALLINT NOT NULL
                            CONSTRAINT chk_detalle_valor CHECK (valor BETWEEN 1 AND 5),
    observacion         TEXT,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_detalle_saber_eje UNIQUE (evaluacion_saber_id, eje_tematico_id)
);

CREATE INDEX idx_det_saber_evaluacion ON detalle_evaluacion_saber(evaluacion_saber_id);
CREATE INDEX idx_det_saber_eje        ON detalle_evaluacion_saber(eje_tematico_id);

COMMENT ON TABLE detalle_evaluacion_saber IS 'Valor asignado a cada eje temático dentro de una evaluación por saber.';

-- ============================================================
-- 6. ALERTAS TEMÁTICAS (generadas por promedios)
-- ============================================================
CREATE TABLE alertas_tematicas (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estudiante_id   BIGINT NOT NULL
                        REFERENCES estudiantes(id) ON DELETE RESTRICT,
    periodo_id      BIGINT NOT NULL
                        REFERENCES periodos(id) ON DELETE RESTRICT,
    eje_tematico_id INT NOT NULL
                        REFERENCES ejes_tematicos(id) ON DELETE RESTRICT,
    promedio         NUMERIC(4,2) NOT NULL,
    nivel_alerta    VARCHAR(15) NOT NULL
                        CONSTRAINT chk_nivel_alerta_tem CHECK (nivel_alerta IN ('ALTA','MEDIA','SIN_ALERTA')),
    motivo          TEXT NOT NULL,
    estado          VARCHAR(15) NOT NULL DEFAULT 'ACTIVA'
                        CONSTRAINT chk_estado_alerta_tem CHECK (estado IN ('ACTIVA','RESUELTA','DESCARTADA')),
    generada_por    BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    fecha_generacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_resolucion TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_alerta_tematica UNIQUE (estudiante_id, periodo_id, eje_tematico_id, nivel_alerta)
);

CREATE INDEX idx_alerta_tem_estudiante ON alertas_tematicas(estudiante_id);
CREATE INDEX idx_alerta_tem_periodo    ON alertas_tematicas(periodo_id);
CREATE INDEX idx_alerta_tem_eje        ON alertas_tematicas(eje_tematico_id);
CREATE INDEX idx_alerta_tem_nivel      ON alertas_tematicas(nivel_alerta);
CREATE INDEX idx_alerta_tem_estado     ON alertas_tematicas(estado);

COMMENT ON TABLE alertas_tematicas IS 'Alertas generadas automáticamente a partir de promedios por eje temático en un periodo.';

-- Trigger updated_at
CREATE TRIGGER trg_alerta_tem_updated_at
    BEFORE UPDATE ON alertas_tematicas
    FOR EACH ROW EXECUTE FUNCTION fn_eval_saber_updated_at();

-- ============================================================
-- 7. VISTA: promedios por eje temático por estudiante/periodo
-- ============================================================
CREATE OR REPLACE VIEW vw_promedios_ejes_periodo AS
SELECT
    es.estudiante_id,
    es.periodo_id,
    det.eje_tematico_id,
    ej.nombre AS eje_nombre,
    ej.tipo_saber_id,
    ts.nombre AS tipo_saber_nombre,
    COUNT(det.id) AS total_evaluaciones,
    ROUND(AVG(det.valor), 2) AS promedio,
    MIN(det.valor) AS valor_minimo,
    MAX(det.valor) AS valor_maximo
FROM detalle_evaluacion_saber det
JOIN evaluaciones_saber es ON es.id = det.evaluacion_saber_id
JOIN ejes_tematicos ej ON ej.id = det.eje_tematico_id
JOIN tipos_saber ts ON ts.id = ej.tipo_saber_id
GROUP BY es.estudiante_id, es.periodo_id, det.eje_tematico_id,
         ej.nombre, ej.tipo_saber_id, ts.nombre;

COMMENT ON VIEW vw_promedios_ejes_periodo IS 'Promedios calculados por eje temático, agrupados por estudiante y periodo.';

-- ============================================================
-- 8. VISTA: promedios por tipo de saber por estudiante/periodo
-- ============================================================
CREATE OR REPLACE VIEW vw_promedios_tipo_saber_periodo AS
SELECT
    v.estudiante_id,
    v.periodo_id,
    v.tipo_saber_id,
    v.tipo_saber_nombre,
    COUNT(DISTINCT v.eje_tematico_id) AS ejes_evaluados,
    ROUND(AVG(v.promedio), 2) AS promedio_tipo_saber
FROM vw_promedios_ejes_periodo v
GROUP BY v.estudiante_id, v.periodo_id, v.tipo_saber_id, v.tipo_saber_nombre;

COMMENT ON VIEW vw_promedios_tipo_saber_periodo IS 'Promedios agregados por tipo de saber, agrupados por estudiante y periodo.';

-- ============================================================
-- 9. DATOS DE EJEMPLO: evaluaciones para los 3 estudiantes seed
-- ============================================================

-- Luis (estudiante_id=1), Período 2 (periodo_id=2), evaluado por María (usuario_id=2), sección 1
-- Primera evaluación: Saber Conceptual
INSERT INTO evaluaciones_saber (estudiante_id, periodo_id, usuario_id, seccion_id, tipo_saber_id, fecha_evaluacion, observacion)
VALUES (1, 2, 2, 1, 1, '2025-04-15', 'Primera evaluación conceptual del periodo');

INSERT INTO detalle_evaluacion_saber (evaluacion_saber_id, eje_tematico_id, valor, observacion) VALUES
(1, 1, 2, 'Dificultad con relación sonido-grafía en dígrafos'),
(1, 2, 1, 'No identifica ideas principales en textos expositivos'),
(1, 3, 2, 'Vocabulario básico limitado para su nivel'),
(1, 4, 2, 'Confunde categorías gramaticales frecuentemente'),
(1, 5, 3, 'Conoce la estructura de texto narrativo'),
(1, 6, 2, 'Identifica solo géneros literarios básicos'),
(1, 7, 2, 'Conoce normas básicas de comunicación oral');

-- Segunda evaluación conceptual (mismo ciclo, para demostrar múltiples evaluaciones)
INSERT INTO evaluaciones_saber (estudiante_id, periodo_id, usuario_id, seccion_id, tipo_saber_id, fecha_evaluacion, observacion)
VALUES (1, 2, 2, 1, 1, '2025-05-10', 'Segunda evaluación conceptual — seguimiento');

INSERT INTO detalle_evaluacion_saber (evaluacion_saber_id, eje_tematico_id, valor, observacion) VALUES
(2, 1, 2, 'Persiste dificultad en lectoescritura'),
(2, 2, 2, 'Leve mejora en comprensión lectora'),
(2, 3, 2, 'Sin cambio significativo'),
(2, 4, 2, 'Sin cambio significativo'),
(2, 5, 3, 'Mantiene buen nivel en producción textual'),
(2, 6, 2, 'Sin cambio'),
(2, 7, 3, 'Mejora en expresión oral');

-- Sofía (estudiante_id=2), Período 2, evaluada por María, sección 1
-- Evaluación Saber Procedimental
INSERT INTO evaluaciones_saber (estudiante_id, periodo_id, usuario_id, seccion_id, tipo_saber_id, fecha_evaluacion, observacion)
VALUES (2, 2, 2, 1, 2, '2025-04-15', 'Evaluación procedimental de Sofía');

INSERT INTO detalle_evaluacion_saber (evaluacion_saber_id, eje_tematico_id, valor, observacion) VALUES
(3, 8,  4, 'Excelentes estrategias de lectoescritura'),
(3, 9,  4, 'Buenas estrategias de comprensión'),
(3, 10, 3, 'Vocabulario contextualizado adecuado'),
(3, 11, 4, 'Muy buen uso gramatical en contexto'),
(3, 12, 5, 'Producción textual sobresaliente'),
(3, 13, 4, 'Buen análisis literario'),
(3, 14, 4, 'Participación oral excelente');

-- Andrés (estudiante_id=3), Período 2, evaluado por María, sección 1
-- Evaluación Saber Actitudinal
INSERT INTO evaluaciones_saber (estudiante_id, periodo_id, usuario_id, seccion_id, tipo_saber_id, fecha_evaluacion, observacion)
VALUES (3, 2, 2, 1, 3, '2025-04-15', 'Evaluación actitudinal de Andrés');

INSERT INTO detalle_evaluacion_saber (evaluacion_saber_id, eje_tematico_id, valor, observacion) VALUES
(4, 15, 1, 'Muy poca disposición hacia la lectoescritura'),
(4, 16, 1, 'No muestra interés por la lectura'),
(4, 17, 2, 'Poca curiosidad léxica'),
(4, 18, 2, 'No valora la corrección lingüística'),
(4, 19, 1, 'Mínimo esfuerzo en tareas de escritura'),
(4, 20, 2, 'Poca sensibilidad literaria'),
(4, 21, 3, 'Participa cuando se le solicita');
